import { convexAuth } from "@convex-dev/auth/server";
import { Password } from "@convex-dev/auth/providers/Password";
import Google from "@auth/core/providers/google";
import Apple from "@auth/core/providers/apple";
import { GenericId } from "convex/values";

// ---------------------------------------------------------------------------
// Convex Auth configuration.
//
// Public sign-up is disabled. Password sign-up requires either:
//   - ADMIN_EMAIL / ADMIN_EMAILS matching the email, for the first admin account.
//   - An unclaimed portal invite code generated by an admin.
//
// Google / Apple remain configured for existing accounts/admin email only; invite
// links use the password flow so the invite code can be checked server-side.
//
// The React client calls `signIn` / `signOut` through `@convex-dev/auth/react`.
//
// Required env vars (set via `npx @convex-dev/auth` and the dashboard):
//   JWT_PRIVATE_KEY, JWKS, SITE_URL, CONVEX_SITE_URL, ADMIN_EMAIL or ADMIN_EMAILS
// ---------------------------------------------------------------------------

function normalizeEmail(value: unknown): string {
  if (typeof value !== "string") throw new Error("Email is required.");
  const email = value.trim().toLowerCase();
  if (!email || !email.includes("@")) throw new Error("A valid email is required.");
  return email;
}

function normalizeInviteCode(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const code = value.trim().toUpperCase();
  return code || undefined;
}

function configuredAdminEmails(): Set<string> {
  return new Set(
    [process.env.ADMIN_EMAIL, process.env.ADMIN_EMAILS]
      .filter((value): value is string => Boolean(value))
      .flatMap((value) => value.split(","))
      .map((value) => value.trim().toLowerCase())
      .filter(Boolean),
  );
}

function isConfiguredAdmin(email: string): boolean {
  return configuredAdminEmails().has(email.toLowerCase());
}

export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [
    Password({
      profile(params) {
        return {
          email: normalizeEmail(params.email),
          accessInviteCode: normalizeInviteCode(params.inviteCode),
        } as any;
      },
    }),
    Google,
    Apple,
  ],
  callbacks: {
    async createOrUpdateUser(ctx, args) {
      const email = normalizeEmail(args.profile.email);
      const now = Date.now();
      const admin = isConfiguredAdmin(email);
      const role = admin ? "admin" : "user";

      if (args.existingUserId !== null) {
        const existingUser = await ctx.db.get(args.existingUserId);
        await ctx.db.patch(args.existingUserId, {
          email,
          role: admin ? "admin" : existingUser?.role ?? role,
          updatedAt: now,
        });
        return args.existingUserId;
      }

      let invite:
        | {
            _id: GenericId<"accessInvites">;
            email?: string;
            role: "admin" | "user";
            claimedByUserId?: GenericId<"users">;
            revokedAt?: number;
            expiresAt?: number;
          }
        | null = null;

      if (!admin) {
        const inviteCode = normalizeInviteCode(args.profile.accessInviteCode);
        if (!inviteCode) {
          throw new Error("Account creation is invite-only.");
        }

        invite = await ctx.db
          .query("accessInvites")
          .withIndex("by_code", (q) => q.eq("inviteCode", inviteCode))
          .unique();

        if (!invite || invite.revokedAt || invite.claimedByUserId) {
          throw new Error("This invite link is no longer valid.");
        }
        if (invite.expiresAt && invite.expiresAt < now) {
          throw new Error("This invite link has expired.");
        }
        if (invite.email && normalizeEmail(invite.email) !== email) {
          throw new Error("This invite link is for a different email address.");
        }
      }

      const userId = await ctx.db.insert("users", {
        email,
        role: admin ? "admin" : invite?.role ?? "user",
        onboardingComplete: false,
        mirrorPaused: false,
        createdAt: now,
        updatedAt: now,
      });

      if (invite) {
        await ctx.db.patch(invite._id, {
          claimedByUserId: userId,
          claimedAt: now,
        });
      }

      return userId;
    },
  },
});
